using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Net;
using Microsoft.Phone.Net.NetworkInformation;
using System.IO;
using Newtonsoft.Json;
using System.Threading;

namespace monorun
{
    public class ApiHandler
    {
        public Boolean isOnline;
		public Highscore LatestHighscore = new Highscore();

        private string serverName = "dev.monorun.com";
        private string apiPath = "/api/api.php";
        private string apiProtocol = "http";
        private string apiUrl = "";
        private string playerid;

		/// <summary>
		/// Initializes and check for API availability
		/// </summary>
		/// <param name="apiAvailableCallback">The callback that should be fired once complete</param>
        public ApiHandler( Action<Object, DownloadStringCompletedEventArgs> apiAvailableCallback )
        {
            apiUrl = apiProtocol + "://" + serverName + apiPath;
            isOnline = CheckForInternetConnection();
            playerid = "";
            if (isOnline) 
            {
                if (apiAvailableCallback != null)
                {
                    // Check that the API is available
                    makeRequest(apiUrl + "?", apiAvailableCallback);
                }
            }
        }

		/// <summary>
		/// Sets connection state (if false, the highscore wont work)
		/// </summary>
		/// <param name="state"></param>
        public void setConnectionState(Boolean state) 
        {
            isOnline = state;
        }

		/// <summary>
		/// Updates highscore with new username
		/// </summary>
		/// <param name="username">The new username</param>
		/// <param name="callback">The callback that should fire on completion</param>
		public void updateScore( String username, Action callback ) 
		{
			if (isOnline == false)
			{
				callback();
				return;
			}

			if (LatestHighscore.secretkey == "") return;
			if (username.Trim() == "") return;

			String url = apiUrl + "?do=update&id=" + LatestHighscore.id + "&username=" + HttpUtility.UrlEncode(username.Trim()) + "&secretkey=" + LatestHighscore.secretkey;
			LatestHighscore.username = username;

			Action<Object, DownloadStringCompletedEventArgs> cb = (o, e) =>
			{
				if (!e.Cancelled && e.Error == null)
				{
					callback();
				}
			};

			makeRequest(url, cb);
		}
		
		/// <summary>
		/// Posts a result to the API
		/// </summary>
		/// <param name="score">The score</param>
		/// <param name="username">The username (if empty, a random will be generated by the API)</param>
		/// <param name="callback">The callback that should fire on completion</param>
        public void postResult( int score, string username, Action callback )
        {
            if (playerid == "" || isOnline == false ) {
				callback();
				return;
			}

            String url = apiUrl + "?do=put&playerid=" + playerid + "&score=" + score + "&sourceid=3";

            Action<Object, DownloadStringCompletedEventArgs> cb = (o, e) =>
             {
                 if (!e.Cancelled && e.Error == null)
                 {
					 try
					 {
						 LatestHighscore = JsonConvert.DeserializeObject<Highscore>( (string) e.Result );
					 }
					 catch (Exception)
					 {
						 // Something is wrong with the API, turn off the connection
						 isOnline = false;
					 }
					 callback();
                 }
             };

            makeRequest(url, cb);
        }

		/// <summary>
		/// Gets the session id for a game (should be fired everytime a game starts)
		/// </summary>
		/// <param name="callback">The callback that should be fired on completion</param>
		public void getSessionId(Action callback)
		{
			if ( isOnline == false )
			{
				callback();
				return;
			}

			String url = apiUrl + "?do=register";

			Action<Object, DownloadStringCompletedEventArgs> cb = (o, e) =>
			{
				if (!e.Cancelled && e.Error == null)
				{
					try
					{
						playerid = JsonConvert.DeserializeObject<String>((string)e.Result);
					}
					catch (Exception)
					{
						// Something is wrong with the API, turn off the connection
						isOnline = false;
					}
					callback();
				}
			};

			makeRequest(url, cb);
		}

		/// <summary>
		/// Gets the top 10 highscores
		/// </summary>
		/// <param name="callback">The callback that should be fired on completion (returns a list with highscores)</param>
		public void getHighscore(Action<List<Highscore>> callback)
		{
			if (isOnline == false)
			{
				callback(new List<Highscore>());
				return;
			}

			String url = apiUrl + "?do=get";

			Action<Object, DownloadStringCompletedEventArgs> cb = (o, e) =>
			{
				if (!e.Cancelled && e.Error == null)
				{
					try
					{
						List<Highscore> list = JsonConvert.DeserializeObject<List<Highscore>>((String)e.Result);
						callback(list);
					}
					catch (Exception)
					{
						// Something is wrong with the API, turn off the connection
						isOnline = false;
						callback(new List<Highscore>());
					}
					
				}
			};

			makeRequest(url, cb);
		}
        
		/// <summary>
		/// Makes a request to the api
		/// </summary>
		/// <param name="url">The api url</param>
		/// <param name="callback">The callback that should be fired with the results</param>
        private void makeRequest( String url, Action<Object, DownloadStringCompletedEventArgs> callback )
        {
            WebClient client = new WebClient();
            Uri uri = new Uri(url);
            if (callback != null) 
            {
                client.DownloadStringCompleted += new DownloadStringCompletedEventHandler(callback);
            }
            client.DownloadStringAsync(uri);
        }

		/// <summary>
		/// Checks for internet connection
		/// </summary>
		/// <returns></returns>
        private Boolean CheckForInternetConnection()
        {
            return (NetworkInterface.NetworkInterfaceType != NetworkInterfaceType.None);
        }

    }
}
